### PR TITLE
Emacs instructions

### PR DESCRIPTION
**Pull request by gottschali**
image

### CODE REVIEW

**Comment by gottschali** [comment]
Needed to use an older abi version: `tree-sitter generate --abi 13`

**Comment by HSMF** [comment]
Thanks a lot!!
- install-emacs.sh seems to be missing
- not sure if we should have install script generate the c source (this will likely mess with git)
also thanks for the examples

**Comment by gottschali** [comment]
- Oopsie will add install-emacs.sh later
- Yes I let the script call treesitter generate which changes parser.c.
I guess a 
git reset parser.c 
or a checkout could restore a clean index afterwards.

**Comment by HSMF** [comment]
LGTM

**Pull request merged**
